### PR TITLE
Add a Development Container for a more seamless local experience

### PR DESCRIPTION
**Pull request by tarebyte**
Hello!

While I was working on https://github.com/chaynHQ/soulmedicine/pull/305 and getting my local environment ready to go, I noticed that there were a lot of dependencies to get setup.

In order to make it easier to contribute, I thought it might be nice to have a way to run it all locally only relying on Docker and potentially VSCode if that is your editor of choice.

This Pull Request introduces a [Dev Container](https://containers.dev) for running the application without having to install any of the necessary dependencies on your machine. It uses the existing services defined in `docker-compose.yml` so that the services running are consistent.

Here's what it looks like in VSCode.

Screenshot 2023-07-02 at 11 49 13

Screenshot 2023-07-02 at 12 06 04

Thanks to using [Ubuntu Jammy](https://releases.ubuntu.com/jammy/) as the [base image](https://github.com/devcontainers/templates/tree/main/src/ubuntu), this can support ARM and Intel based machines.

If this is a path we'd like to move forward with, I'm happy to make changes to the README to show this as an option when getting started.

Thanks!

### CODE REVIEW

**Comment by eleanorreem** [comment]
Hey ! Thank you for this! I didn't have my notifications turned on so I didn't see this PR. This all makes sense to me. I will look through this today

**Comment by tarebyte** [comment]
No rush at all, thanks so much for taking a look!

**Comment by eleanorreem** [comment]
I think this approach is great. I didn't know about dev containers so this is a great new addition. Thank you! I couldn't quite get this one working but I assume with start up instructions that I will be able to 😄

**Review by issyl0 — APPROVED** [review]
This works for me!

**Comment by tarebyte** [comment]
> Thank you! I couldn't quite get this one working (most likely my lack of understanding) but I assume with start up instructions that I will be able to 😄

I'll update the README/documentation before merging.

**Pull request merged**
